name: Daily Commit

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check latest commit date
        id: check_date
        run: |
          if git log -1 --format=%cd --date=short > /dev/null 2>&1; then
            LATEST_DATE=$(git log -1 --format=%cd --date=short)
            TODAY=$(date +%Y-%m-%d)
            if [ "$LATEST_DATE" = "$TODAY" ]; then
              echo "Already committed today. Skipping."
              echo "skip=true" >> $GITHUB_OUTPUT
            else
              echo "No commit today. Proceeding."
              echo "skip=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No commits yet. Proceeding."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Make daily commits
        if: steps.check_date.outputs.skip == 'false'
        run: |
          NUM_COMMITS=$((RANDOM % 3 + 6))  # Random 6-8
          echo "Making $NUM_COMMITS commits today."
          for i in $(seq 1 $NUM_COMMITS); do
            TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
            echo "$TIMESTAMP - Commit $i" >> streak.txt
            git add streak.txt
            git commit -m "Daily commit $i: $TIMESTAMP"
            git push
          done
